version: "3"

volumes:
  prismatica-core-configs: {}

  ambassador-config: {}

  core-mongo-storage: {}
  core-mongo-config: {}

  vault-config: {}
  vault-logs: {}
  vault-file: {}

services:

  prismatica-infrastructure:
    image: quay.io/project-prismatica/prismatica-infrastructure:latest
    command:
    - "/bin/sh"
    - "-c"
    - >
      mkdir -p /prismatica-core-configs/ambassador/config &&
      cp -r /prismatica-infrastructure/ambassador/* \
        /prismatica-core-configs/ambassador/config/ &&
      date > /prismatica-core-configs/copied-timestamp
    volumes:
    - "prismatica-core-configs:/prismatica-core-configs:Z"

  prismatica-core:
    image: quay.io/project-prismatica/prismatica-core:latest
    depends_on:
      - prismatica-infrastructure
    environment:
      CORE_AMBASSADOR_SOURCE_CONFIG_DIR: "/source-configs/ambassador/config"
      CORE_AMBASSADOR_CONFIG_DIR: "/external-configs/ambassador/"
      DEBUG: 1
    expose:
    - 8080
    volumes:
    - "ambassador-config:/external-configs/ambassador/config:Z"
    - "prismatica-core-configs:/source-configs:Z"

  prismatica-idam:
    image: quay.io/project-prismatica/prismatica-idam:latest
    depends_on:
      - prismatica-infrastructure
    environment:
      IDAM_BIND: "0.0.0.0:8080"
      IDAM_DEBUG: "1"
    expose:
    - 8080

  prismatica-rootui:
    image: quay.io/project-prismatica/prismatica-rootui:latest
    depends_on:
      - prismatica-infrastructure
    environment:
      ROOT_URL: "http://prismatica-rootui/"
      MONGO_URL: "mongodb://core-mongo:27017/rootui"
      WAIT_FOR: "core-mongo:27017"
      WAIT_FOR_FAIL: "true"
      WAIT_FOR_SECONDS: 30
    expose:
    - 3000

  ambassador:
    image: quay.io/datawire/ambassador:0.29.0
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - "ambassador-config:/etc/ambassador-config:Z"

  core-mongo:
    image: mongo
    expose:
    - "27017"
    volumes:
    - "core-mongo-storage:/data/db:Z"
    - "core-mongo-config:/data/configdb:Z"

  vault:
    image: vault
    env_file:
    - "vault/environment"
    expose:
    - "8200"
    volumes:
    - "vault-config:/vault/config:Z"
    - "vault-logs:/vault/logs:Z"
    - "vault-file:/vault/file:Z"
